esphome:
  name: dryer
  friendly_name: dryer

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "nMD4QOr8CXAp1r7+cFPRCRaKc2N+cenXeGbsgXcpxBE="

ota:
  - platform: esphome
    password: "b0602654baa82a91f124180a782e9626"

wifi:
  ssid: "makerspace.lt"
  password: "100 decibelu"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dryer Fallback Hotspot"
    password: "vBQJlP5mWUU0"

web_server:
  port: 80
  ota: false
  version: 3
  local: true

captive_portal:

one_wire:
  platform: gpio
  pin: 32



sensor:
  - platform: hx711
    name: "Load Cell Weight"
    dout_pin: 13  # Changed from 13
    clk_pin: 12    # Changed from 14
    gain: 128
    update_interval: 5s
    id: load_cell
    filters:
      - calibrate_linear:
        - 35000 -> 0
        - 450000 -> 1000.0 
    on_value:
      then:
        - lambda: |
            if (id(load_cell).state > id(target_weight).state) {
              id(heat).turn_off();
              id(drying_fan).turn_off();
              id(blender).turn_off();
            }

  - platform: dallas_temp
    #address: 0x32 #todo: add real address
    name: "Drying Temperature"
    id: drying_temp_sensor
    on_value:
      then:
        - lambda: |
            if (id(drying_temp_sensor).state < id(drying_temp).state + 1) {
              id(heat).turn_on();
            } else {
              id(heat).turn_off();
            }

switch:
  - platform: gpio
    pin: 33
    id: heat
    name: "Heating Element"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 4
    id: drying_fan
    name: "Drying Fan"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 22
    id: blender
    name: "Blender"
    restore_mode: ALWAYS_OFF

  - platform: template
    name: "Move Conveyor"
    turn_on_action:
      - stepper.set_target:
          id: conveyor_motor
          target: 1000


stepper:
  - platform: a4988
    id: conveyor_motor
    step_pin: 26
    dir_pin: 27
    max_speed: "1 steps/s"

number:
  - platform: template
    name: "Target Weight"
    id: target_weight
    optimistic: true
    min_value: 1
    max_value: 10000000
    step: 1

  - platform: template
    name: "Drying Temperature"
    id: drying_temp
    optimistic: true
    min_value: 1
    max_value: 100
    step: 1

  - platform: template
    name: "Conveyor Speed"
    id: conveyor_speed
    optimistic: true
    min_value: 1
    max_value: 100
    step: 1
